### ISSUE TITLE
Make centres choice optional

### ISSUE THREAD

**Issue by 520rahul** [DivAgicha/CoWIN-Vaccine-Appointment-Booking#10]
In ur repo v have to choose a centre from the available center list which is shown only after slots are released by cowin, otherwise no center are shown for selection. Plz make changes in repo so that it automatically pick up any centre which fulfils our other conditions instead of selecting centers which have already gone

**Comment by divagicha** [comment]
It's already optional in the script!! If you don't want to enter any particular centre name and want the script to match based on other criteria just hit enter without entering anything, when asked for centre preferences. It is clearly mentioned in the suggestion as "CAN BE BLANK AS WELL", when it asks for centre preferences.

**Comment by 520rahul** [comment]
> It's already optional in the script!! If you don't want to enter any particular centre name and want the script to match based on other criteria just hit enter without entering anything, when asked for centre preferences. It is clearly mentioned in the suggestion as "CAN BE BLANK AS WELL", when it asks for centre preferences.

Ok thanks. I shall update u once i check it.  One more thing can b reduce 3 sec time to 1 sec and which api do u use for searching and can u add bearer token file so that 15 min session can b run without any problem if session get closed. And one more suggestion keep slot booking on auto book mode if any slot is found instead of waiting for our confirmation for slot timing or other things because it is matter of fraction of seconds. Hope u will consider the same

**Comment by 520rahul** [comment]
@divagicha

**Comment by divagicha** [comment]
1. Time of 3 sec has been decided to make a total of 80 attempts, i.e., script will run for 4 mins, this is because API has a limit of 100 calls per 5 min per IP. If it exceeds that limit IP automatically gets blocked by the server.
2. Bearer token is already being saved into a file for persistence. Script always uses the saved token while making requests to the API. If already existing token generates 'Unauthenticated Response', a new token is requested from the API.
3. Script already has an option to select slot preference. If you want not to be asked for the slot timing and randomly pick up a slot at runtime, select 'Randomly select a slot' option instead of 'Enter manually when a valid centre is found'.

**Comment by 520rahul** [comment]
> * Time of 3 sec has been decided to make a total of 80 attempts, i.e., script will run for 4 mins, this is because API has a limit of 100 calls per 5 min per IP. If it exceeds that limit IP automatically gets blocked by the server.
> * Bearer token is already being saved into a file for persistence. Script always uses the saved token while making requests to the API. If already existing token generates 'Unauthenticated Response', a new token is requested from the API.
> * Script already has an option to select slot preference. If you want not to be asked for the slot timing and randomly pick up a slot at runtime, select 'Randomly select a slot' option instead of 'Enter manually when a valid centre is found'.

Thanks for clearing doubts 👏🏻👍🏻
