### ISSUE TITLE
Documentation for building in Windows

### ISSUE THREAD

**Issue by techantidote** [DivAgicha/CoWIN-Vaccine-Appointment-Booking#16]
-Add section on how to contribute for Windows, compile and create the final exe

**Comment by divagicha** [comment]
Due to my current working schedule I won't be able to provide documentation for the same, anytime soon. However, you can find various blogs over the internet for the same.

Python library used for compiling py scripts to exe: pyinstaller
Application used to combine all files and generate windows installer: NSIS
