### ISSUE TITLE
Validating the OTP to get token not working

### ISSUE THREAD

**Issue by yashmmehta90** [DivAgicha/CoWIN-Vaccine-Appointment-Booking#3]
-->	Enter OTP received on your mobile phone (Press 'Enter' to resend OTP): 507362

-->	Validating 'OTP' to get token

FAILED ATTEMPT (message: Expecting value: line 1 column 1 (char 0)) (response: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: h-PlLM5mCb89M7dFmkVuId-dWD3imszMzOoiohEvP74QSU8ztGaXQQ==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>)

-->	Generating OTP (There might be some delay in receiving the OTP, please wait atleast 2 minutes)

txnId: bf79352f-e7c5-46a7-a933-083da829976a	(SUCCESS)

-->	Enter OTP received on your mobile phone (Press 'Enter' to resend OTP): 507362

-->	Validating 'OTP' to get token

FAILED ATTEMPT (message: 'token') (response: {"message": "Endpoint request timed out"})

-->	Generating OTP (There might be some delay in receiving the OTP, please wait atleast 2 minutes)

FAILED ATTEMPT (message: Expecting value: line 1 column 1 (char 0)) (response: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: kZT9AVTq6DNU-7EbwQSE5PqvfVV9kAor57v1kAm7p_T3SDIRgc4ESw==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>)... trying again in 3 seconds

**Comment by divagicha** [comment]
Thanks for bringing this up. As per the screenshot you have mentioned above, '{"message": "Endpoint request timed out"}', it is likely that you lost your internet connectivity while the script was still running as it implies that the server has decided to close the connection rather than continue waiting.
Kindly check for some little things which might have caused this issue to arise on the system as mentioned below.

Few things to keep in mind:
1. Indian Govt's CoWIN platform has a rate limit of 100 requests in 5 min. If your system exceeds this limit, your IP will be automatically blocked for a while till you can make any request again.
2. If you are running this via the python script '.py' file, make sure you don't alter the the values of 'User-Agent' and 'secret' variables in '\_\_init\_\_.py'
3. Make sure you are not using any proxy while making requests as CoWIN platform has a server-side check for not serving requests originating from outside India.
4. Cross check that you have good and stable internet connectivity.
5. Last and highly unlikely, CoWIN server might have been down for a while, possibly due to heavy load on the server.

**Comment by yashmmehta90** [comment]
Thanks for your revert. Reviewed your points and here are my thoughts below:
1. In regards to IP getting blocked, I have no way of knowing. 
2. Haven't. changed any part of the original code.  I just let it run until it ends and then restart it using the same preset settings.
3. Not using a proxy as well
4. Checked the internet connection repeatedly and it seems fine
5. I have no way of knowing if Cowin is down. 

I have even tried running the same code on another laptop but it didnt help. Getting the same error. It asks me for the OTP, then tries to validate the token, then fails saying "End point request timed out". Then it puts in another request for a new OTP, but no new OTP is coming to my mobile phone.  I have even tried it on three different internet connections on two different computers. Honestly not sure where the problem is.

**Comment by divagicha** [comment]
After numerous checks of the requests made in the script and cross-checking them with official CoWIN API I found out that they have now implemented yet another check to **serve requests originating from their servers only and ignoring all the others**. This change was made on the servers yesterday. I've now **updated the scripts** accordingly. Program is working fine and as expected now. Let me know if it worked on your end too.

**Comment by yashmmehta90** [comment]
Thanks for your help, got my first slot.  Really appreciate it.

**Comment by divagicha** [comment]
Glad this script could help!! Cheers
