### ISSUE TITLE
Change Date to Onwards Date & Vaccine Type

### ISSUE THREAD

**Issue by Coy-sys1** [DivAgicha/CoWIN-Vaccine-Appointment-Booking#6]
A big thank you for the script and your time invested. This is very helpful. 

Can we add a feature to filter by Vaccine Type. But most importantly change from a specific date search to search from date range n + 1 for 7 days

Thank you once again

**Comment by divagicha** [comment]
@Coy-sys1  I'm glad you liked this application. And also the suggestions that you have mentioned here as the feature request.

This application was developed as a proof-of-concept project only. As such, it has all the basic functionality that a normal user would perform on the official CoWIN portal for scheduling an appointment. Due to my current job schedule I'm not sure as to when I'll be able to make the updates for the new feature. However, everyone is welcome to contribute to this project.

Thanks
